import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fafafa',
    paddingHorizontal: 20,
    paddingTop: 20,
    alignItems: 'center',
  },
  gridWrapper: {
    flex: 1,
    width: '100%',
    maxWidth: 1200, // Reasonable maximum width
    maxHeight: 500, // Reasonable maximum height to ensure scrollbars
    borderRadius: 12,
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    overflow: 'hidden',
    marginHorizontal: 'auto', // Center the grid
  },
  stickyHeaderContainer: {
    backgroundColor: '#ffffff',
    borderBottomWidth: 2,
    borderBottomColor: '#e5e7eb',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 5,
    zIndex: 2, // Ensure header stays on top
  },
  headerScrollView: {
    flexGrow: 0,
  },
  dataContainer: {
    flex: 1,
    position: 'relative',
  },
  dataScrollView: {
    flexGrow: 0,
  },
  verticalScrollView: {
    flex: 1,
    maxHeight: 400, // Ensure vertical scrolling appears when needed
  },
  verticalScrollContainer: {
    flexGrow: 1,
    paddingBottom: 20, // Add padding at the bottom for better UX
  },
  outerVerticalScrollView: {
    flex: 1,
    maxHeight: 450, // Ensure vertical scrolling appears
  },
  outerVerticalScrollContainer: {
    flexGrow: 1,
  },
  horizontalScrollView: {
    borderRadius: 12,
  },
  horizontalScrollContainer: {
    flexGrow: 1,
  },
  horizontalScrollableContent: {
    backgroundColor: '#fff',
    paddingHorizontal: 20,
  },
  dataHorizontalScrollView: {
    flex: 1,
  },
  horizontalScrollbarContainer: {
    height: 20,
    backgroundColor: '#f8f8f8',
    borderTopWidth: 1,
    borderTopColor: '#ddd',
  },
  bottomHorizontalScrollView: {
    height: 20,
  },
  horizontalScrollPlaceholder: {
    height: 1,
    backgroundColor: 'transparent',
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: '100%',
  },
  gridContainer: {
    backgroundColor: 'transparent', // Remove background since wrapper has it
    paddingHorizontal: 20,
    paddingBottom: 20,
    minWidth: '100%',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    width: '100%',
    maxWidth: 1200,
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: 12,
  },
  evaluateButton: {
    backgroundColor: '#10b981',
    borderColor: '#10b981',
  },
  evaluateButtonText: {
    color: '#ffffff',
  },
  title: {
    fontSize: 28,
    fontWeight: '300',
    color: '#1f2937',
    letterSpacing: 0.5,
  },
  addButton: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  addRowButton: {
    backgroundColor: '#3b82f6',
    borderColor: '#3b82f6',
  },
  addButtonText: {
    color: '#374151',
    fontWeight: '500',
    fontSize: 13,
  },
  addRowButtonText: {
    color: '#ffffff',
  },
  headerRow: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    borderBottomWidth: 2,
    borderBottomColor: '#f3f4f6',
    paddingVertical: 4,
  },
  headerCell: {
    paddingVertical: 8,
    paddingHorizontal: 8,
    fontWeight: '600',
    color: '#6b7280',
    textAlign: 'left',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    justifyContent: 'center',
    alignItems: 'flex-start',
    outline: 'none'
  },
  headerCellText: {
    fontWeight: '600',
    color: '#6b7280',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginHorizontal: 8,
    outline: 'none'
  },
  editableHeaderCell: {
    backgroundColor: '#fbf9f9ff',
    borderRadius: 4,
    position: 'relative',
    paddingVertical: 4,
    paddingHorizontal: 4,
    overflow: 'hidden',
  },
  nonEditableHeaderText: {
    opacity: 0.7,
  },
  editingHeaderCell: {
    backgroundColor: '#ffffff',
    borderRadius: 6,
    paddingVertical: 4,
    paddingHorizontal: 4,
    overflow: 'hidden',
    outline: 'none'
  },
  headerInput: {
    fontSize: 12,
    color: '#520707ff',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    paddingVertical: 4,
    paddingHorizontal: 4,
    minHeight: 21,
    outline: 'none',
    width: '100%',
  },
  dataRow: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#f9fafb',
  },
  cell: {
    paddingVertical: 16,
    paddingHorizontal: 12,
    justifyContent: 'center',
    minHeight: 52,
  },
  cellText: {
    fontSize: 15,
    color: '#111827',
    fontWeight: '400',
  },
  editingCell: {
    paddingVertical: 8,
    paddingHorizontal: 8,
    backgroundColor: '#ffffff',
    borderRadius: 6,
    outline: 'none'
  },
  formulaEditingCell: {
    borderColor: '#10b981',
    backgroundColor: '#f0fdf4',
    outline: 'none'
  },
  textInput: {
    color: '#111827',
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  formulaTextInput: {
    fontFamily: 'monospace',
    color: '#059669',
  },
  formulaHint: {
    fontSize: 10,
    color: '#6b7280',
    fontStyle: 'italic',
    marginTop: 2,
  },
  errorEditingCell: {
    backgroundColor: '#fef2f2',
    borderColor: '#dc2626',
    borderWidth: 2,
    outline: 'none',
    shadowColor: '#dc2626',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  errorTextInput: {
    color: '#dc2626',
  },
  errorHint: {
    fontSize: 10,
    color: '#dc2626',
    fontStyle: 'italic',
    marginTop: 2,
    fontWeight: '500',
  },
  circularDependencyHint: {
    fontSize: 11,
    color: '#dc2626',
    fontStyle: 'italic',
    marginTop: 2,
    fontWeight: '600',
    backgroundColor: '#fef2f2',
    padding: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#fca5a5',
  },
  errorContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
  cancelErrorButton: {
    backgroundColor: '#dc2626',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 8,
  },
  cancelErrorText: {
    color: '#ffffff',
    fontSize: 9,
    fontWeight: '500',
  },
  errorCell: {
    backgroundColor: '#fef2f2',
    borderLeftWidth: 3,
    borderLeftColor: '#dc2626',
    borderWidth: 1,
    borderColor: '#fca5a5',
  },
  errorCellText: {
    color: '#dc2626',
  },
  errorIndicator: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: '#dc2626',
    borderRadius: 8,
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorIndicatorText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  hoveredCell: {
    backgroundColor: '#f0f9ff',
    borderColor: '#3b82f6',
    borderWidth: 1,
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
  },
  errorOverlay: {
    position: 'absolute',
    zIndex: 1000,
    minWidth: 250,
    maxWidth: 350,
  },
  errorTooltip: {
    backgroundColor: '#1f2937',
    borderRadius: 8,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  errorTooltipTitle: {
    color: '#f87171',
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  errorTooltipMessage: {
    color: '#ffffff',
    fontSize: 11,
    lineHeight: 16,
    marginBottom: 4,
  },
  errorTooltipSuggestion: {
    color: '#fbbf24',
    fontSize: 10,
    fontStyle: 'italic',
    lineHeight: 14,
  },
  errorTooltipArrow: {
    position: 'absolute',
    left: -6,
    top: 12,
    width: 0,
    height: 0,
    borderTopWidth: 6,
    borderBottomWidth: 6,
    borderRightWidth: 6,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderRightColor: '#1f2937',
  },
  hoverErrorPreview: {
    position: 'absolute',
    zIndex: 999,
    backgroundColor: '#fef2f2',
    borderColor: '#fca5a5',
    borderWidth: 1,
    borderRadius: 6,
    padding: 8,
    minWidth: 200,
    maxWidth: 300,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  hoverErrorText: {
    color: '#dc2626',
    fontSize: 10,
    lineHeight: 14,
  },
  globalErrorOverlay: {
    position: 'absolute',
    top: 100,
    left: 20,
    right: 20,
    zIndex: 10000,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    borderRadius: 12,
    padding: 4,
  },
  errorPanel: {
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fca5a5',
    borderRadius: 8,
    margin: 16,
    padding: 12,
    maxHeight: 200,
  },
  errorPanelTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#dc2626',
    marginBottom: 8,
    textAlign: 'center',
  },
  errorItem: {
    backgroundColor: '#ffffff',
    borderRadius: 6,
    padding: 8,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#dc2626',
  },
  errorItemCell: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#374151',
    marginBottom: 2,
  },
  errorItemMessage: {
    fontSize: 11,
    color: '#dc2626',
    marginBottom: 4,
    lineHeight: 16,
  },
  errorItemAction: {
    fontSize: 10,
    color: '#3b82f6',
    fontStyle: 'italic',
    textAlign: 'right',
  },
  errorTooltipInstruction: {
    color: '#3b82f6',
    fontSize: 11,
    fontStyle: 'italic',
    marginTop: 8,
    textAlign: 'center',
  },
  formulaCell: {
    backgroundColor: '#f0fdf4',
    borderLeftWidth: 3,
    borderLeftColor: '#10b981',
    borderWidth: 0,
  },
  formulaCellText: {
    color: '#059669',
    fontFamily: 'monospace',
    borderWidth: 0,
  },
  formulaIndicator: {
    position: 'absolute',
    top: 2,
    right: 2,
    fontSize: 8,
    color: '#10b981',
    fontWeight: 'bold',
    backgroundColor: '#ffffff',
    paddingHorizontal: 2,
    borderRadius: 2,
  },
  actionColumn: {
    width: 80,
  },
  deleteButton: {
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    marginVertical: 8,
    marginHorizontal: 4,
  },
  deleteButtonText: {
    color: '#dc2626',
    fontWeight: '500',
    fontSize: 13,
  },
  editingOverlay: {
    position: 'absolute',
    bottom: 30,
    left: 20,
    right: 20,
    backgroundColor: '#1f2937',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 5,
    borderWidth: 0,
  },
  editingText: {
    color: '#f9fafb',
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '400',
  },
});
